workflows:
  flutter-ios:
    name: Advanced iOS Build & Deploy
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APPLE_DEVELOPER_TEAM: "YOUR_TEAM_ID"
        IOS_EXPORT_METHOD: "app-store"
        BUNDLE_ID: "com.example.app"
    scripts:
      - name: Install Flutter Dependencies
        script: flutter pub get
      - name: Install CocoaPods Dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: flutter build ipa --export-method $IOS_EXPORT_METHOD
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    integrations:
      app_store_connect: ${{ inputs.app_store_integration }}
    publishing:
      app_store_connect:
        auth: ${{ inputs.app_store_integration }}
